// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaeiXA0fY3OjE_xidbh7wjoAguLjOBNI8',
    appId: '1:1067148987292:web:c864d8d35d37efaa011659',
    messagingSenderId: '1067148987292',
    projectId: 'my-finance-00',
    authDomain: 'my-finance-00.firebaseapp.com',
    storageBucket: 'my-finance-00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhrMJyO5GxGv6qre-11ILCPFQ5wGBU0M',
    appId: '1:1067148987292:android:bd70ab5f7fe4f3c5011659',
    messagingSenderId: '1067148987292',
    projectId: 'my-finance-00',
    storageBucket: 'my-finance-00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV54HuyDXTodZhZV_O7YJaQLGM7jw6klA',
    appId: '1:1067148987292:ios:ebcab364f98e0989011659',
    messagingSenderId: '1067148987292',
    projectId: 'my-finance-00',
    storageBucket: 'my-finance-00.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV54HuyDXTodZhZV_O7YJaQLGM7jw6klA',
    appId: '1:1067148987292:ios:ebcab364f98e0989011659',
    messagingSenderId: '1067148987292',
    projectId: 'my-finance-00',
    storageBucket: 'my-finance-00.firebasestorage.app',
    iosBundleId: 'com.example.myFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaeiXA0fY3OjE_xidbh7wjoAguLjOBNI8',
    appId: '1:1067148987292:web:5178d5436921ff7e011659',
    messagingSenderId: '1067148987292',
    projectId: 'my-finance-00',
    authDomain: 'my-finance-00.firebaseapp.com',
    storageBucket: 'my-finance-00.firebasestorage.app',
  );
}
